### ISSUE TITLE
model field error

### ISSUE THREAD

**Issue by skbohra** [caffeinehit/django-follow#16]
(1054, "Unknown column 'follow_follow.target_user_id' in 'where clause'") 

I have checked the latest code from the repo, has anything changed lately?

**Comment by frbry** [comment]
I'm having this issue too.

**Comment by digitalpbk** [comment]
i'm having this too, guess we are supposed to manually alter the follow table and add the field target_ classname|lower _id ? 
@flashingpumpkin 

This happened because I did syncdb and then did the utils.register code change, probably need to use a database migration app south to handle migrations and db changes

**Comment by flashingpumpkin** [comment]
@digitalpbk, @frbry 

You need to register Django models _before_ running syncdb. If you do not do it, you'll run into this issue. You can fix it by creating a South migration. This might have to be documented.
